commit change to TS

diff --git a/.github/workflows/truffle_security-BC-scan.yml b/.github/workflows/truffle_security-BC-scan.yml
--- a/.github/workflows/truffle_security-BC-scan.yml
+++ b/.github/workflows/truffle_security-BC-scan.yml
@@ -26,6 +26,13 @@ jobs:
       env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}
 
+    - name: Check for secrets file
+      run: |
+        if [[ ! -f trufflehog-secrets.json ]]; then
+          echo "Secrets file not found!"
+          exit 1
+        fi
+
     - name: Monitor secrets with Snyk
       uses: trufflesecurity/trufflehog@main
       #with: 
