commit up to TS

diff --git a/.github/workflows/truffle_security-BC-scan.yml b/.github/workflows/truffle_security-BC-scan.yml
--- a/.github/workflows/truffle_security-BC-scan.yml
+++ b/.github/workflows/truffle_security-BC-scan.yml
@@ -6,11 +6,11 @@ on:
       - main
   pull_request:
 
-permissions: 
-  contents: read 
-  id-token: write 
-  issues: write 
-  pull-requests: write
+#permissions: 
+ # contents: read 
+  #id-token: write 
+#  issues: write 
+ # pull-requests: write
 
 
 jobs:
@@ -25,28 +25,28 @@ jobs:
       uses: trufflesecurity/trufflehog@main
       with:
         extra_args: --only-verified
-  TruffleHog: 
-    runs-on: ubuntu-latest 
-    defaults: 
-      run: 
-        shell: bash 
-    steps: 
-      - name: Checkout code 
-        uses: actions/checkout@v3 
-        with: 
-          fetch-depth: 0
-      - name: TruffleHog OSS 
-        id: trufflehog 
-        uses: trufflesecurity/trufflehog@add-actions-cli-switch 
-        continue-on-error: true 
-        with: 
-          path: ./ 
-          base: "${{ github.event.repository.default_branch }}" 
-          head: HEAD 
-          extra_args: --debug --only-verified
-      - name: Scan Results Status 
-        if: steps.trufflehog.outcome == 'failure' 
-        run: exit 1
+  #TruffleHog: 
+   # runs-on: ubuntu-latest 
+    #defaults: 
+     # run: 
+      #  shell: bash 
+    #steps: 
+     # - name: Checkout code 
+      #  uses: actions/checkout@v3 
+       # with: 
+        #  fetch-depth: 0
+#      - name: TruffleHog OSS 
+ #       id: trufflehog 
+  #      uses: trufflesecurity/trufflehog@add-actions-cli-switch 
+   #     continue-on-error: true 
+    #    with: 
+     #     path: ./ 
+      #    base: "${{ github.event.repository.default_branch }}" 
+       #   head: HEAD 
+        #  extra_args: --debug --only-verified
+ #     - name: Scan Results Status 
+  #      if: steps.trufflehog.outcome == 'failure' 
+   #     run: exit 1
 
 
 
