commit change

diff --git a/.github/workflows/truffle_security-BC-scan.yml b/.github/workflows/truffle_security-BC-scan.yml
--- a/.github/workflows/truffle_security-BC-scan.yml
+++ b/.github/workflows/truffle_security-BC-scan.yml
@@ -21,17 +21,19 @@ jobs:
       uses: trufflesecurity/trufflehog@main
       with:
         extra_args: --only-verified 
-        output: trufflehog-secrets.sarif
+        output: trufflehog-secrets.json
       continue-on-error: true
       env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}
 
-   # - name: Check for secrets file
-    #  run: |
-     #   if [[ ! -f trufflehog-secrets.json ]]; then
-      #    echo "Secrets file not found!"
-       #   exit 1
-       # fi
+    - name: Check for secrets file
+      run: |
+        if [[ ! -f trufflehog-secrets.json ]]; then
+          echo "Secrets file not found!"
+          exit 1
+        fi
+
+      
 
     - name: Monitor secrets with Snyk
       #uses: trufflesecurity/trufflehog@main
@@ -39,7 +41,7 @@ jobs:
       #with: 
           #command: monitor
       with:   
-          command: monitor --all-sub-projects --json-file=trufflehog-secrets.sarif
+          command: monitor --all-sub-projects --json-file=trufflehog-secrets.json
           #output: trufflehog-secrets.sarif
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}  # Use the Snyk Auth Token
